#!/bin/bash

# Program to output a system info page

TITLE="System Information Report For $HOSTNAME"
CURRENT_TIME=$(date +"%x %r %Z")
TIMESTAMP="Generated $CURRENT_TIME, by $USER"

report_uptime () {
    echo "report_uptime"
    return
}

report_disk_space () {
    echo "report_disk_space"
    return
}

report_home_space () {
    echo "report_home_space"
    return
}


cat << _EOF_
echo "<HTML>
    <HEAD>
        <TITLE>$TITLE</TITLE>
    </HEAD>
    <BODY>
        <H1>$TITLE</H1>
        <P>$TIMESTAMP</P>
        $(report_uptime)
        $(report_disk_space)
        $(report_home_space)
    </BODY>
</HTML>"
_EOF_
