#!/bin/bash

# program to output system information
TITLE="System Information Report for $USER"
CURRENT_TIME=$(date +"%x %r %Z")
TIMESTAMP="Generated at $CURRENT_TIME by $USER"


report_uptime () {
    echo "System uptime: $(uptime)"
    return 
}

cat << _EOF_
<HTML>
  <HEAD>
      <TITLE>$TITLE</TITLE>
  </HEAD>
  <BODY>
      <H1>$TITLE</H1>
      <P>$TIMESTAMP</P>
      $(report_uptime)
  </BODY>
</HTML>
_EOF_
